version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3003

  backend:
    build: ./backend
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=3003
      - SECRET=${SECRET}
